### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by Kronos568** [SpectralVectors/RightMouseNavigation#11] opened 2022-06-15 10:52 UTC
It would be better if the object context menu opens at double right click or [RightMouseNavigation] works at double right click . vice versa. two things working in one click is kind of have a buglike look.
Thanks for the addOn . awesome

**Comment by SpectralVectors** [comment] 2022-06-15 12:38
Hi, the addon was designed to bring Unreal Engine style navigation to Blender, which uses a single right mouse click to perform navigation or open context menus.

I did a quick test to see what would happen if one was reassigned to a double click, but it didn't work for me.

What happened was:
- whatever you assigned to a single click happens first, no matter how fast you double click
- once you have single clicked with right mouse, it resets the 'click counter' and registers the double click as another single click
- this means that you will get a context menu, then get the 'Add quick shortcut' menu, but never actually get the navigation
- or you will enter navigation and never get the context menu

If you are able to get that feature working you can submit a pull request to have it merged into the addon, but I'm not sure that it's possible (at least not without setting up some kind of logic that tells it to ignore your first mouse click, which seems like it could be annoying in a different kind of way).

Thanks for checking out the addon!

**Closed by SpectralVectors** 2022-06-15 12:38 UTC

**Comment by Kronos568** [comment] 2022-06-15 15:42
bro u knw better than me.
at least its working.
So, can i turn off context menu completely??
because i can't turn it off after installing the addon

**Comment by SpectralVectors** [comment] 2022-06-15 16:41
Hmm, if you go into Edit > Preferences > Addons > RightMouseNavigation and disable it, the controls will return to Blender's default.

Blender's default is Shift+` to go into Navigation mode, you could remap that to whatever you wanted.

The context menus are the tricky bit, and part of the reason why the whole thing is an addon, and not just a couple of changes to the keymap. 

Every area in Blender has a different context menu, and some areas have more than one (the 3D Viewport has one each for: Object, Vertex, Edge, Face, Sculpt, Weight Paint, Texture Paint.) So, any change you want to make, you need to make across every area that has a context menu, remapping it to whatever command you want it to be, which is a bit of a pain in the butt. I make a list in the addon, then loop through the list with code, but to do it manually is pretty tedious.

Context menus are bound to Right mouse by default unless you choose Right click select. If that's the case, you can always tell Blender to revert the user preferences, which will return it to the same state it was right after you installed it.

There is one more option if you want to use the addon: in Edit > Preferences > Addons > RightMouseNavigation, you will find a movement and time threshold, you can adjust these to determine when a menu should open vs when you should enter navigation.

If you want to remove context menus entirely, you can search the keymap for anything called "menu" and disable it, but I think you're going to miss those context menus when they're gone.
